### ISSUE TITLE
Example tetris course is not xAPI compliant

### ISSUE THREAD

**Issue by joshuapaling** [adlnet/experienceapi_client_examples#71]
It expects the actor to have an mbox property. We're using this as an example package to test our LMS, where we're using an 'account' as a Inverse Function Identifier (and therefore our actor doesn't have an mbox), and it breaks as a result. Docs: https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#inversefunctional

The version of tetris you can download at https://tincanapi.com/download-prototypes/ works fine.

**Comment by creighton** [comment]
Glad the other prototype example works for you. This is a simple example and not intended to support every feature of xAPI. However, mbox is a valid IFI for an agent. I'm sorry it's not the IFI you were looking for. 

By the way, if you're testing an LRS, may I recommend using https://github.com/adlnet/lrs-conformance-test-suite, which is a test suite for LRSs. Also, the Testing Requirements doc lists the requirements w/in the spec: https://github.com/adlnet/xAPI_LRS_Test/blob/master/TestingRequirements.md
